name: Build VinzzRenderer APK

on:
  push:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout VinzzRenderer-plugin
        uses: actions/checkout@v4
        with:
          path: VinzzRenderer-plugin

      - name: Checkout VinzzRenderer core
        uses: actions/checkout@v4
        with:
          repository: VinzzLK/VinzzRenderer
          path: VinzzRenderer
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;27.3.13750724"

      - name: Link core into plugin
        run: |
          cp -r VinzzRenderer/MobileGlues-cpp VinzzRenderer-plugin/MobileGlues/MobileGlues-cpp

      - name: Build Debug APK
        run: |
          cd VinzzRenderer-plugin
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VinzzRenderer-debug
          path: VinzzRenderer-plugin/app/build/outputs/apk/debug/*.apk
